name: Semgrep

on:
  pull_request: {}

  push:
    branches: ["master", "main"]
    
  schedule:
    - cron: '30 0 1,15 * *' 

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: returntocorp/semgrep-action@549796168c0ddcb9149b10a0e79e5f6522f50797
        with:
          config: >-
            p/security-audit
            p/secrets
            p/ci
            p/r2c
            p/r2c-ci
            p/docker
            p/dockerfile
            p/command-injection
